service: app

provider:
    name: aws
    region: ap-south-1

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: src/index.php
        description: ''
        runtime: php-82-fpm
        timeout: 28 
        events:
            - httpApi:
                path: /{proxy+}
                method: ANY

    api2:
        handler: src/chat.php
        description: ''
        runtime: php-82-fpm
        timeout: 28 
        events:
            - httpApi:
                path: /chat.php
                method: ANY

    api3:
        handler: src/title.php
        description: ''
        runtime: php-82-fpm
        timeout: 28 
        events:
            - httpApi:
                path: /title.php
                method: ANY

# Exclude files from deployment
package:
    patterns:
        - '!.github/**'
        - '!src/static/**'
        - '!node_modules/**'
